version: "3.8"

services:
  # Redis for Celery broker
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # Celery Worker
  worker:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432/cmgmtDB
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    mem_limit: 4g # limit memory to 2GB
    cpus: 2 # limit CPU to 1.5 cores
    volumes:
      - ./.:/app/
    command: celery -A celery_app worker  --loglevel=info

  # Celery Beat (scheduler)
  beat:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432/cmgmtDB
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

    command: celery -A celery_app beat  --loglevel=info --schedule=/tmp/celerybeat-schedule

  # Flask App (if needed)
  # app:
  #   build: .
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/cmgmtDB
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #   command: python app.py
